### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by leyuan-sun** [pioneer-innovation/Zero-Shot-Object-Navigation#4]
File "main.py", line 225, in <module>
    main()
  File "main.py", line 206, in main
    f = open(save_path, "a")
FileNotFoundError: [Errno 2] No such file or directory: '/trained_models/SA_18_4/SelfAttention_test_runs/mjolnir_train-2024-04-08_18-41-46.txt'

**Comment by leyuan-sun** [comment]
How to save the tranied model?

**Comment by Sky-railway** [comment]
hey guys, Please read the readme.md  carefully , which has been mentioned that: "Note: the folder to save trained model should be set up before training."  Do you make the folder before training？
